In [13]:
import numpy as np
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print('2D array:')
print(a)

b = a[1:2,0:4]
print('slice consist of second row all columns: ', b)

b = a[1:2,1:2]
print('slice consists of second row second column: ', b)

b= a[:2, 0:2]
print('slice consist of two rows first [1,2] and second[5,6]: ') 
print(b)

b= a[:2, 1:3]
print('slice consist of two rows first [2,3] and second[6,7]: ') 
print(b)

b= a[1:3, 2:4]
print('slice consist of two rows first [7,8] and second[11,12]: ') 
print(b)

2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
slice consist of second row all columns:  [[5 6 7 8]]
slice consists of second row second column:  [[6]]
slice consist of two rows first [1,2] and second[5,6]: 
[[1 2]
 [5 6]]
slice consist of two rows first [2,3] and second[6,7]: 
[[2 3]
 [6 7]]
slice consist of two rows first [7,8] and second[11,12]: 
[[ 7  8]
 [11 12]]
