In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

data=pd.read_csv('iris-csv.csv')
data.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [3]:
x=data.iloc[:,:-1].values
y=data.iloc[:,4].values

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [8]:
y_pred=knn.predict(x_test)
print("accuracy",metrics.accuracy_score(y_test,y_pred))

accuracy 0.9666666666666667


In [9]:
sample=([[4.3,5.2,1.3,0.1]])
knn.predict(sample)

array(['Setosa'], dtype=object)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix
print("Confusion matrix")
print(confusion_matrix(y_test, y_pred))
print("Classification Report")
print(classification_report(y_test, y_pred))


Confusion matrix
[[11  0  0]
 [ 0 10  1]
 [ 0  0  8]]
Classification Report
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      0.91      0.95        11
   Virginica       0.89      1.00      0.94         8

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30

